//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 抽卡
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Product_Total
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_Product_Total()
        {
            this.Game_Item_Purchase_Record = new HashSet<Game_Item_Purchase_Record>();
        }
    
        public string Product_Name { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Product_Category_ID { get; set; }
        public string Product_Description { get; set; }
        public Nullable<int> Product_Price { get; set; }
        public byte[] Product_Image { get; set; }
        public string Purchased_Quantity { get; set; }
        public string Remaining_Quantity { get; set; }
        public Nullable<decimal> Lottery_Probability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Item_Purchase_Record> Game_Item_Purchase_Record { get; set; }
        public virtual Game_Product_Category Game_Product_Category { get; set; }
    }
}
