//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Shop部落格資料表
    {
        public int 部落格文章ID { get; set; }
        public string 文章標題 { get; set; }
        public string 文章內容 { get; set; }
        public System.DateTime 發布時間 { get; set; }
        public int 管理員ID { get; set; }
        public bool 是否顯示 { get; set; }
        public bool 是否置頂 { get; set; }
        public bool 是否要在遊戲商城同步顯示 { get; set; }
        public int 文章類型ID { get; set; }
    
        public virtual Game_shop_文章類型資料庫 Game_shop_文章類型資料庫 { get; set; }
        public virtual Shop_Game_後臺管理員資料 Shop_Game_後臺管理員資料 { get; set; }
    }
}
