//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_扭蛋紀錄表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_扭蛋紀錄表()
        {
            this.Game_背包物品總表 = new HashSet<Game_背包物品總表>();
        }
    
        public int 會員ID { get; set; }
        public int 扭蛋ID { get; set; }
        public System.DateTime 扭蛋時間 { get; set; }
        public string 獎品_遊戲內_ { get; set; }
        public Nullable<int> 獎品_優惠券ID_ { get; set; }
        public int 扭蛋紀錄表ID { get; set; }
    
        public virtual Shop_會員資訊 Shop_會員資訊 { get; set; }
        public virtual Shop_優惠券總表 Shop_優惠券總表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_背包物品總表> Game_背包物品總表 { get; set; }
    }
}
