//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_角色資訊
    {
        public byte[] 會員ID { get; set; }
        public string 角色名稱 { get; set; }
        public string 角色等級 { get; set; }
        public string 角色裝備 { get; set; }
        public string 角色物品 { get; set; }
        public int 扭蛋券數量 { get; set; }
        public int 遊戲幣數量 { get; set; }
        public int 折抵幣數量 { get; set; }
    }
}
