//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_商品總表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_商品總表()
        {
            this.Game_物品購買紀錄表 = new HashSet<Game_物品購買紀錄表>();
            this.Game_寵物 = new HashSet<Game_寵物>();
        }
    
        public string 商品名稱 { get; set; }
        public int 商品ID { get; set; }
        public int 產品類別ID { get; set; }
        public string 商品描述 { get; set; }
        public int 商品價格 { get; set; }
        public byte[] 商品圖片 { get; set; }
        public string 已被購買數量 { get; set; }
        public string 產品剩餘數量 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_物品購買紀錄表> Game_物品購買紀錄表 { get; set; }
        public virtual Game_商品類別表 Game_商品類別表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_寵物> Game_寵物 { get; set; }
    }
}
