//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Global_Chat_Data
    {
        public Nullable<int> Member_ID { get; set; }
        public int Message_ID { get; set; }
        public string Message_Content { get; set; }
        public Nullable<System.DateTime> Sent_Time { get; set; }
        public Nullable<bool> Hide_Message { get; set; }
    
        public virtual Shop_Member_Info Shop_Member_Info { get; set; }
    }
}
