//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_任務總表
    {
        public int 任務ID { get; set; }
        public string 任務名稱 { get; set; }
        public string 任務描述 { get; set; }
        public decimal 任務獎勵 { get; set; }
        public int 任務條件ID { get; set; }
    
        public virtual Game_任務條件資料表 Game_任務條件資料表 { get; set; }
        public virtual Game_會員任務 Game_會員任務 { get; set; }
    }
}
