//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_會員B訊息資料表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_會員B訊息資料表()
        {
            this.Game_好友列表聊天室資料表 = new HashSet<Game_好友列表聊天室資料表>();
        }
    
        public int 會員_B_ID { get; set; }
        public string C_訊息_發送者_內容 { get; set; }
        public Nullable<System.DateTime> 發送時間 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_好友列表聊天室資料表> Game_好友列表聊天室資料表 { get; set; }
    }
}
