//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_貓幣兌換紀錄
    {
        public int 會員ID { get; set; }
        public System.DateTime 兌換時間 { get; set; }
        public int 兌換數量 { get; set; }
        public int 貓幣兌換紀錄ID { get; set; }
    
        public virtual Shop_會員資訊 Shop_會員資訊 { get; set; }
    }
}
