//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_寵物
    {
        public int 商品ID { get; set; }
        public int 寵物ID { get; set; }
        public int 寵物等級ID { get; set; }
        public int 寵物技能ID { get; set; }
        public int 寵物稀有度ID { get; set; }
    
        public virtual Game_商品總表 Game_商品總表 { get; set; }
    }
}
