//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_成就總表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_成就總表()
        {
            this.Game_角色成就 = new HashSet<Game_角色成就>();
        }
    
        public int 成就ID { get; set; }
        public string 成就名稱 { get; set; }
        public int 成就獎勵ID { get; set; }
        public int 成就條件ID { get; set; }
    
        public virtual Game_任務條件資料表 Game_任務條件資料表 { get; set; }
        public virtual Game_成就獎勵總表 Game_成就獎勵總表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_角色成就> Game_角色成就 { get; set; }
    }
}
