//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_我的最愛資料表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_我的最愛資料表()
        {
            this.Shop_商品總表1 = new HashSet<Shop_商品總表>();
        }
    
        public int 會員ID { get; set; }
        public int 我的最愛ID { get; set; }
        public int 商品ID { get; set; }
        public int 建立日期 { get; set; }
    
        public virtual Shop_商品總表 Shop_商品總表 { get; set; }
        public virtual Shop_會員資訊 Shop_會員資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_商品總表> Shop_商品總表1 { get; set; }
    }
}
