//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_訂單總表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_訂單總表()
        {
            this.Shop_訂單明細表 = new HashSet<Shop_訂單明細表>();
            this.Shop_退換貨資料表 = new HashSet<Shop_退換貨資料表>();
        }
    
        public int 會員ID { get; set; }
        public int 訂單ID { get; set; }
        public System.DateTime 訂單成立日期 { get; set; }
        public System.DateTime 最後更新時間 { get; set; }
        public int 收件地址 { get; set; }
        public int 收件姓名 { get; set; }
        public int 收件電話 { get; set; }
        public int 訂單狀態ID { get; set; }
        public int 付款方式ID { get; set; }
        public Nullable<int> 優惠券ID { get; set; }
    
        public virtual Shop_付款方式資料表 Shop_付款方式資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_訂單明細表> Shop_訂單明細表 { get; set; }
        public virtual Shop_訂單狀態資料表 Shop_訂單狀態資料表 { get; set; }
        public virtual Shop_會員資訊 Shop_會員資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_退換貨資料表> Shop_退換貨資料表 { get; set; }
    }
}
