//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_會員客訴案件表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_會員客訴案件表()
        {
            this.Shop_回覆資料表 = new HashSet<Shop_回覆資料表>();
        }
    
        public int 客訴案件ID { get; set; }
        public string 申訴標題 { get; set; }
        public int 會員ID { get; set; }
        public string 客訴內容 { get; set; }
        public int 客訴狀態ID { get; set; }
        public int 申訴類別ID { get; set; }
        public System.DateTime 建立時間 { get; set; }
    
        public virtual Shop_申訴類別資料表 Shop_申訴類別資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_回覆資料表> Shop_回覆資料表 { get; set; }
        public virtual Shop_客訴狀態資料表 Shop_客訴狀態資料表 { get; set; }
        public virtual Shop_會員資訊 Shop_會員資訊 { get; set; }
    }
}
