//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_會員資訊
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_會員資訊()
        {
            this.Game_1on1訊息資料表 = new HashSet<Game_1on1訊息資料表>();
            this.Game_1on1訊息資料表1 = new HashSet<Game_1on1訊息資料表>();
            this.Game_全頻道聊天資料表 = new HashSet<Game_全頻道聊天資料表>();
            this.Game_好友資料表 = new HashSet<Game_好友資料表>();
            this.Game_扭蛋紀錄表 = new HashSet<Game_扭蛋紀錄表>();
            this.Game_角色成就 = new HashSet<Game_角色成就>();
            this.Game_會員任務 = new HashSet<Game_會員任務>();
            this.Game_貓幣兌換紀錄 = new HashSet<Game_貓幣兌換紀錄>();
            this.Shop_我的最愛資料表 = new HashSet<Shop_我的最愛資料表>();
            this.Shop_訂單總表 = new HashSet<Shop_訂單總表>();
            this.Shop_商品評論表 = new HashSet<Shop_商品評論表>();
            this.Shop_常用地址資料表 = new HashSet<Shop_常用地址資料表>();
            this.Shop_會員折價券資料表 = new HashSet<Shop_會員折價券資料表>();
            this.Shop_會員客訴案件表 = new HashSet<Shop_會員客訴案件表>();
            this.Game_背包物品總表 = new HashSet<Game_背包物品總表>();
            this.Shop_購物車 = new HashSet<Shop_購物車>();
        }
    
        public int 會員ID { get; set; }
        public string 會員帳號 { get; set; }
        public string 角色名稱 { get; set; }
        public int 等級ID { get; set; }
        public string 密碼 { get; set; }
        public string 姓名 { get; set; }
        public string 性別 { get; set; }
        public Nullable<System.DateTime> 生日 { get; set; }
        public string 電子郵件 { get; set; }
        public string 手機號碼 { get; set; }
        public string 地址 { get; set; }
        public int 貓幣數量 { get; set; }
        public int 紅利數量 { get; set; }
        public System.DateTime 註冊時間 { get; set; }
        public System.DateTime 最後登入時間 { get; set; }
        public int 我的最愛ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_1on1訊息資料表> Game_1on1訊息資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_1on1訊息資料表> Game_1on1訊息資料表1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_全頻道聊天資料表> Game_全頻道聊天資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_好友資料表> Game_好友資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_扭蛋紀錄表> Game_扭蛋紀錄表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_角色成就> Game_角色成就 { get; set; }
        public virtual Game_等級排位資料表 Game_等級排位資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_會員任務> Game_會員任務 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_貓幣兌換紀錄> Game_貓幣兌換紀錄 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_我的最愛資料表> Shop_我的最愛資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_訂單總表> Shop_訂單總表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_商品評論表> Shop_商品評論表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_常用地址資料表> Shop_常用地址資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_會員折價券資料表> Shop_會員折價券資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_會員客訴案件表> Shop_會員客訴案件表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_背包物品總表> Game_背包物品總表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_購物車> Shop_購物車 { get; set; }
    }
}
