//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatChaForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Coupon_Total
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_Coupon_Total()
        {
            this.Shop_Member_Coupon_Data = new HashSet<Shop_Member_Coupon_Data>();
        }
    
        public int Coupon_ID { get; set; }
        public string Coupon_Name { get; set; }
        public string Coupon_Content { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<int> Total_Quantity { get; set; }
        public Nullable<bool> Usable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Member_Coupon_Data> Shop_Member_Coupon_Data { get; set; }
    }
}
