//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_回覆資料表
    {
        public int 回覆ID { get; set; }
        public int 客訴案件ID { get; set; }
        public int 接收者ID_官方_ { get; set; }
        public string 訊息_接收者_內容 { get; set; }
        public System.DateTime 發送時間 { get; set; }
    
        public virtual Shop_Game_後臺管理員資料 Shop_Game_後臺管理員資料 { get; set; }
        public virtual Shop_會員客訴案件表 Shop_會員客訴案件表 { get; set; }
    }
}
