//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_商品總表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_商品總表()
        {
            this.Shop_我的最愛資料表 = new HashSet<Shop_我的最愛資料表>();
            this.Shop_訂單明細表 = new HashSet<Shop_訂單明細表>();
            this.Shop_商品評論表 = new HashSet<Shop_商品評論表>();
            this.Shop_商品圖片表 = new HashSet<Shop_商品圖片表>();
            this.Shop_我的最愛資料表1 = new HashSet<Shop_我的最愛資料表>();
        }
    
        public string 商品名稱 { get; set; }
        public int 商品ID { get; set; }
        public int 產品類別ID { get; set; }
        public string 商品描述 { get; set; }
        public decimal 商品價格 { get; set; }
        public string 尺寸 { get; set; }
        public string 重量 { get; set; }
        public System.DateTime 上架日期 { get; set; }
        public bool 是否停售 { get; set; }
        public int 已被購買數量 { get; set; }
        public int 產品剩餘數量 { get; set; }
        public int 供應商ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_我的最愛資料表> Shop_我的最愛資料表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_訂單明細表> Shop_訂單明細表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_商品評論表> Shop_商品評論表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_商品圖片表> Shop_商品圖片表 { get; set; }
        public virtual Shop_商品類別表 Shop_商品類別表 { get; set; }
        public virtual Shop_產品供應商 Shop_產品供應商 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_我的最愛資料表> Shop_我的最愛資料表1 { get; set; }
    }
}
