//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatChaEntities.backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_CheckIn
    {
        public int MemberID { get; set; }
        public Nullable<bool> Day1 { get; set; }
        public Nullable<bool> Day2 { get; set; }
        public Nullable<bool> Day3 { get; set; }
        public Nullable<bool> Day4 { get; set; }
        public Nullable<bool> Day5 { get; set; }
        public Nullable<bool> Day6 { get; set; }
        public Nullable<bool> Day7 { get; set; }
        public Nullable<bool> Day8 { get; set; }
        public Nullable<bool> Day9 { get; set; }
        public Nullable<bool> Day10 { get; set; }
        public Nullable<bool> Day11 { get; set; }
        public Nullable<bool> Day12 { get; set; }
        public Nullable<bool> Day13 { get; set; }
        public Nullable<bool> Day14 { get; set; }
    
        public virtual Shop_Member_Info Shop_Member_Info { get; set; }
    }
}
