//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatChaEntities.backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Favorite_Data_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_Favorite_Data_Table()
        {
            this.Shop_Product_Total1 = new HashSet<Shop_Product_Total>();
        }
    
        public Nullable<int> Member_ID { get; set; }
        public int Favorite_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Creation_Date { get; set; }
    
        public virtual Shop_Product_Total Shop_Product_Total { get; set; }
        public virtual Shop_Member_Info Shop_Member_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_Product_Total> Shop_Product_Total1 { get; set; }
    }
}
