//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormResize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Shop_Blog_Data
    {
        public int Blog_Article_ID { get; set; }
        public string Article_Title { get; set; }
        public string Article_Content { get; set; }
        public Nullable<System.DateTime> Publish_Time { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public Nullable<bool> Display_Status { get; set; }
        public Nullable<bool> Pin_to_Top { get; set; }
        public Nullable<bool> Sync_with_Game_and_Shop_Display { get; set; }
        public Nullable<int> Article_Type_ID { get; set; }
    
        public virtual Game_shopArticleType Game_shopArticleType { get; set; }
        public virtual Shop_Game_Admin_Data Shop_Game_Admin_Data { get; set; }
    }
}
