//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormResize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Return_Data_Table
    {
        public int Order_ID { get; set; }
        public Nullable<int> Return_Reason_ID { get; set; }
        public Nullable<int> Processing_Status_ID { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
    
        public virtual Shop_Return_Reason_Data_Table Shop_Return_Reason_Data_Table { get; set; }
        public virtual Shop_Return_Status_Data_Table Shop_Return_Status_Data_Table { get; set; }
    }
}
