//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha.ZongHan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_shopArticleType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_shopArticleType()
        {
            this.Game_Shop_Blog_Data = new HashSet<Game_Shop_Blog_Data>();
        }
    
        public int ArticleTypeID { get; set; }
        public string ArticleTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Shop_Blog_Data> Game_Shop_Blog_Data { get; set; }
    }
}
