//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha.ZongHan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Member_B_Message_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_Member_B_Message_Data()
        {
            this.Game_Friend_List_Chat_Data = new HashSet<Game_Friend_List_Chat_Data>();
        }
    
        public int Member__B__ID { get; set; }
        public string C_訊息_發送者_內容 { get; set; }
        public Nullable<System.DateTime> Sent_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_Friend_List_Chat_Data> Game_Friend_List_Chat_Data { get; set; }
    }
}
