//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace buttonHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatChaEntities : DbContext
    {
        public CatChaEntities()
            : base("name=CatChaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Shop_Common_Address_Data> Shop_Common_Address_Data { get; set; }
        public virtual DbSet<Shop_Coupon_Total> Shop_Coupon_Total { get; set; }
        public virtual DbSet<Shop_Member_Coupon_Data> Shop_Member_Coupon_Data { get; set; }
        public virtual DbSet<Shop_Member_Info> Shop_Member_Info { get; set; }
        public virtual DbSet<Shop_Order_Detail_Table> Shop_Order_Detail_Table { get; set; }
        public virtual DbSet<Shop_Order_Status_Data> Shop_Order_Status_Data { get; set; }
        public virtual DbSet<Shop_Order_Total_Table> Shop_Order_Total_Table { get; set; }
        public virtual DbSet<Shop_Payment_Method_Data> Shop_Payment_Method_Data { get; set; }
        public virtual DbSet<Shop_Product_Category> Shop_Product_Category { get; set; }
        public virtual DbSet<Shop_Product_Image_Table> Shop_Product_Image_Table { get; set; }
        public virtual DbSet<Shop_Product_Total> Shop_Product_Total { get; set; }
    }
}
