//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCaha.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Pet
    {
        public Nullable<int> Product_ID { get; set; }
        public int Pet_ID { get; set; }
        public Nullable<int> Pet_Level_ID { get; set; }
        public Nullable<int> Pet_Skill_ID { get; set; }
        public Nullable<int> Pet_Rarity_ID { get; set; }
    
        public virtual Game_Product_Total Game_Product_Total { get; set; }
    }
}
