//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatChaEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Character_Info
    {
        public byte[] Member_ID { get; set; }
        public string Character_Name { get; set; }
        public string Character_Level { get; set; }
        public string Character_Equipment { get; set; }
        public string Character_Items { get; set; }
        public int Gacha_Ticket_Quantity { get; set; }
        public int Game_Coin_Quantity { get; set; }
        public int Discount_Coin_Quantity { get; set; }
    }
}
