//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatChaEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Reply_Data
    {
        public int Reply_ID { get; set; }
        public int Complaint_Case_ID { get; set; }
        public int Receiver_ID__Official_ { get; set; }
        public string Message__Recipient__Content { get; set; }
        public System.DateTime Sent_Time { get; set; }
    
        public virtual Shop_Game_Admin_Data Shop_Game_Admin_Data { get; set; }
        public virtual Shop_Member_Complaint_Case Shop_Member_Complaint_Case { get; set; }
    }
}
